### ISSUE TITLE
docker : not usable and/or not documented

### ISSUE THREAD

**Issue by vingerha** [bdbogjoe/pronote-rest#2]
Tried v1.0.1 but it complains about missing config.json. Even adding a config folder mapping with config.json in it....continues to complain. Possibly missing a basic setup?

**Comment by bdbogjoe** [comment]
you have to mount folder config to /app/config

**Comment by vingerha** [comment]
Doesn't work, and my comment was also because there is no documentation, if you share things on forums you should also make it attractive imo...but that is me
```
docker run --name=pronotebdbogjoe -it --net=host --restart=unless-stopped -v /home/arjan/docker/pronotebd:/app/config bdbogjoe/pronote-rest:v1.0.1
```
error:
```
Traceback (most recent call last):
  File "/home/app/app.py", line 281, in <module>
    with open('config/config.json') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'config/config.json'
```
in /home/arjan/docker/pronotebd  I have the config.json, I even added a config folder on top with the same config.json

**Comment by bdbogjoe** [comment]
it should be in config folder

ie : /home/arjan/docker/pronotebd/config/config.json

**Comment by bdbogjoe** [comment]
or you can use : -v /home/arjan/docker/pronotebd/config.json:/app/config/config.json

**Comment by bdbogjoe** [comment]
as info i added docker-compose.yml as example

**Comment by vingerha** [comment]
That is what I wrote.... I have 
/home/arjan/docker/pronotebd/config/config.json AND 
/home/arjan/docker/pronotebd/config/config/config.json
error remains

**Comment by vingerha** [comment]
read the compose now and I now sse it was HOME/app/config to map to... above in your repsonse it lacked the 'home' part... now I get other errors but that is expected :)

**Comment by vingerha** [comment]
After resolving the port issue (I have 5000 already in use)...it seems to hang...any idea ?
![image](https://user-images.githubusercontent.com/44190435/213442725-025532cd-1522-4881-b247-102d73ab0e81.png)

**Comment by bdbogjoe** [comment]
i updated the readme

**Comment by vingerha** [comment]
And I continue to have issues with port 5000...  can I avoid this container to use p5000?

**Comment by bdbogjoe** [comment]
nothing is hanging you have to connect to http://localhost:6000

**Comment by bdbogjoe** [comment]
you were right i forgot /home prefix, i updated the readme

**Comment by vingerha** [comment]
> nothing is hanging you have to connect to http://localhost:6000

Thanks and will try later, work-pc does not allow to connect to NUC this way.... curl from nas>nuc kicks back the html though
so...later

**Comment by vingerha** [comment]
I cannot get this to work for some odd reason.
This is my docker run
```
 docker run --name=pronotebdbogjoe -it -p 6000:5000 --restart=unless-stopped -v /home/arjan/docker/pronotebd:/home/app/config bdbogjoe/pronote                                                                                                   -rest:master
```
and this is what it shows in the log
```
 * Serving Flask app 'app'
 * Debug mode: off
2023-01-24 15:11:53,169 - werkzeug - INFO - WARNING: This is a development serve                                                                                                   r. Do not use it in a production deployment. Use a production WSGI server instea                                                                                                   d.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.17.0.11:5000
2023-01-24 15:11:53,169 - werkzeug - INFO - Press CTRL+C to quit
```

Now, if I use the ip and 6000, http(s)://192.168.1.xx:6000   then nothing returns (This site can't be reached) 

EDIT: I put it on my NUC and same issues, I opened port 6000 too (ufw)
EDIT2: it works with p5000:5000 but I have another container on 5000 :( (I shut it down just to test)

**Comment by ioull** [comment]
Did you try ssh on  the docker machine and try wget http://localhost:6000 ? to be aware of firewall rules ?
